RBrooks:
StarcubeLabs/7DRLChallenge2023 pull request #3
Opened 2023-03-08 05:13 UTC by rukiab

-Added Floor Data.
-Added  Current Floor Data to Level Controller.
-Added Floor Data to Level Manager.
-Commented out Trap code due to error.

2023-03-08 18:24 UTC, AnonymousRandomPerson requested changes

2023-03-08 18:24 UTC, AnonymousRandomPerson commented on Assets/Scripts/ItemScripts/ItemData.cs
> -    public string ItemName;
Why was this changed?

2023-03-08 18:37 UTC, AnonymousRandomPerson commented on Assets/Scripts/LevelController.cs
>      public List<EntityController> entitiesOnLevel = new List<EntityController>();
An exception occurs when you get a game over and try to respawn.

2023-03-09 01:24 UTC, rukiab commented on Assets/Scripts/ItemScripts/ItemData.cs
> -    public string ItemName;
Since we're not using scriptable objects, I don't see the point in separating out ItemData into a separate class especially since we're not doing this with other entities. I think this is better as its less files to have to deal with. That being said I'm okay with changing it back.  I would like to do this for traps too.

Also this now means we can change the line 205 in LevelController, to just get a randomized entry from the WeightedTable instead of assigning data.

2023-03-09 03:57 UTC, rukiab commented on Assets/Scripts/LevelController.cs
>      public List<EntityController> entitiesOnLevel = new List<EntityController>();
This has been fixed, basically the issue was the WeightedTable weight wasn't reset and we were reconstructing the weighted table every scene change. So what I decided to do was A). Not reconstruct the weighted table but I did reset the TotalWeight to 0, just in case.

2023-03-09 04:01 UTC, AnonymousRandomPerson requested changes
Fix merge conflicts.

2023-03-09 05:11 UTC, AnonymousRandomPerson commented on Assets/Scripts/ItemScripts/ItemData.cs
> -    public string ItemName;
From an organizational standpoint, it's useful to separate the constant attributes of item types from individual item instances.

2023-03-10 02:27 UTC, closed without merging